### ISSUE TITLE
Editieransicht des Videoblocks überarbeiten

### ISSUE THREAD

**Issue by xabbuh** [virtUOS/mooc.ip#150]
Die UI des Autorenmodus des Videoblocks muss generell überarbeitet werden:

- [ ] Suchmaske für Matterhorn-Videos
- [x] Eingabe der Video-ID für YouTube-Videos
- [ ] Generierung eines ``video``-Tags bei der Einbindung reiner Videodateien über eine URL
- [ ] angezeigte Höhe und Breite des Videos sollte konfigurierbar sein (Seitenverhältnisse beibehalten)
- [x] Validierung von Benutzereingaben auf Plausibilität
- [x] Präsentation aussagekräftiger Fehlermeldungen
- [x] Startzeit Minuten:Sekunden eingeben

**Comment by tthelen** [comment]
Good enough right now.
