### ISSUE TITLE
Konfigurationsseite für das Plugin

### ISSUE THREAD

**Issue by tthelen** [virtUOS/mooc.ip#194]
Es soll einige globale Konfigurationsoptionen für das Plugin geben, die von Root verändert werden können.

1. Konfigurationsseite anlegen und nur für Root zugänglich machen
2. Konfigurationsoption "Startseite oder nur Kursliste" einbauen. Wenn "Nur Kursliste" gewählt wird, gibt es keine Übersichtsseite, sondern nur die Kursliste. Wenn "Startseite" ausgewählt ist, gibt es wie bislang Übersichtsseite und Kursliste.

Später können weitere Optionen hinzukommen.

**Comment by luniki** [comment]
Brauchen wir das wirklich bis zum OHN-Starttermin oder ist das ein backlog :older_man: ?

**Comment by tthelen** [comment]
Das können Konfiguirationsoptionen werden, wenn man's mal braucht.
