### ISSUE TITLE
Sidebar ausblenden für Kapitelbaum

### ISSUE THREAD

**Issue by tthelen** [virtUOS/mooc.ip#201]
Der Navigationsbereich soll in eine Sidebar verpackt werden, sobald die GUIs sich geeinigt haben.

Dann soll der Abschnittstitel direkt über den Abschnittsicons stehen, löst auch #192 

Till sagt Lucas bescheid, wenn es soweit ist.

**Comment by tgloeggl** [comment]
* Sidebar ausblenden
* Navigationspunkte an anderer Stelle platzieren
    * Für Studierende statt des Modusumschalters ein Icon/Text mit Link zur Fortschrittsanzeige
    * Import/Export ans Ende der Baumstruktur. Admins sind informiert, wo sie suchen sollen.

**Comment by luniki** [comment]
Rein technisch müsste das jetzt passen.
Das optische muss überprüft werden. Außerdem für die 3.0 und 2.5 checken.

**Comment by luniki** [comment]
Ich mache ein neues Issue auf, um dort den Kapitelbaum in die Sidebar zu stecken.

**Comment by xabbuh** [comment]
2.5 unterstützen wir ja eh nicht.
