### ISSUE TITLE
Sortieren und Kopieren von Unterkapiteln und Abschnitten

### ISSUE THREAD

**Issue by rlucke** [virtUOS/mooc.ip#242]
Es wäre sehr schön wenn man Unterkapitel auch in andere Kapitel verschieben könnte. Die gleiche Freiheit wäre auch für Abschnitte wünschenswert. Auch eine Kopierfunktion von Abschnitten und Unterkapiteln wäre hilfreich.

**Comment by tthelen** [comment]
s. https://github.com/virtUOS/courseware/issues/69
