### ISSUE TITLE
MOOC-Dauer: Zeitangabe fehlt.

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/mooc.ip#245]
Unter Verwaltung → Grunddaten gibt es den Punkt MOOC-Dauer. Leider ist nicht klar, welche Angabe dort hinein muss. Die Dauer in Wochen?

**Comment by CGreweling** [comment]
@tthelen  ist das noch aktuell?

**Comment by tthelen** [comment]
Das kommt ein String rein, der die Dauer beschreibt, z.B. "6 Wochen" oder "50 Stunden Selbststudium" oder "mindestens 3 Monate".

**Comment by CGreweling** [comment]
@luniki @tthelen könnte man hier evtl. das als Beispieltext hinterlegen? Kann mir jemand zeigen wo man das einbauen kann?
