### ISSUE TITLE
Test- und Blubberblock nur verwenden, wenn Blubber und Vips aktiv sind 

### ISSUE THREAD

**Issue by rlucke** [virtUOS/mooc.ip#301]
In der Veranstaltungskategorie (M)OOC-artiges müssen die Inhaltselemente Blubber und Vips auf "Standart aktiv" gesetzt werden, da sonst die entsprechenden Blöcke nicht funktionieren.

**Comment by xabbuh** [comment]
@CGreweling Ist das nicht so? Und inwiefern ist das für Blubber noch relevant?

**Comment by CGreweling** [comment]
Ich konnte diesen Fehler nicht nachvollziehen und wollte nicht dass das in vergessenheit gerät, deswegen die zuweisung. Sollten wir Donnerstag kurz drüber sprechen

**Comment by luniki** [comment]
Es macht mehr Sinn sicherzustellen, dass Vips und Blubber aktiviert sind, wenn man solche Blöcke anfasst. Selbst wenn Vips und Blubber standard-aktiv sind, heißt das nicht, dass sie das immer sein werden. Gerade beim Im/Export kann sowas schnell mal passieren.
