### ISSUE TITLE
(Un-)Besuchte Abschnitte markanter markieren

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/mooc.ip#308]
Derzeit sieht man nicht besonders gut, ob man einen Abschnitt bereits besucht hat. Im HTML wird der ".section" die CSS-Klasse ".visited" zugeordnet, aber nur wenig/nicht ausgestaltet.

**Comment by tthelen** [comment]
s. https://github.com/virtUOS/courseware/issues/67
