### ISSUE TITLE
Übersichtsseite fehlt bei frischer Installation

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/mooc.ip#312]
Bei den Veranstaltungskategorien muss im Bereich Übersicht "Mooc.IP" als "Standard Aktiv" markiert und darf nicht "Wählbar" sein.
Das sollte bei der entsprechenden Datenbankmigration berücksichtigt werden.

**Comment by luniki** [comment]
Das hängt sicher mit #300 zusammen?!

**Comment by tgloeggl** [comment]
Ja, das ist genau das dort beschriebene Problem, dieses Ticket ist demnach ein Duplikar
