### ISSUE TITLE
Mooc Preview Video

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#319]
Grunddaten->Beschreibung->M)OOC-Preview-Video (mp4)
Wo wird das angezeigt.
Warum nicht auch hier einfügbar wie in einem Block über Youtube-URL?

**Comment by xabbuh** [comment]
Wir können ein Vorschaubild automatisch anhand der ID des YouTube-Videos wählen, wenn keine Bildadresse eingegeben wurde.
