### ISSUE TITLE
Kurse Inhalt Sichtbar abhängig vom Startdatum?

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#323]
Alle Kurse um Kurs /Mehr je nach Startdatum?

**Comment by CGreweling** [comment]
vorläufiges eintragen
Und dann via cronjob aktualisieren

**Comment by luniki** [comment]
Wie man Cronjobs in Stud.IP integriert:

http://docs.studip.de/develop/Entwickler/Cronjobs
