### ISSUE TITLE
Testblock: richtig beantwortete Fragen besser hervorheben

### ISSUE THREAD

**Issue by xabbuh** [virtUOS/mooc.ip#326]
Im Moment ist nicht sofort ersichtlich, welche Fragen durch den Nutzer korrekt beantwortet wurden. Es wird angezeigt, welche Antwortmöglichkeiten korrekt waren und welche Antworten der Nutzer ausgewählt hat. Aus diesen beiden Ausgaben muss man so selbst schließen, ob die Frage korrekt beantwortet wurde (welche Antworten korrekt waren).

**Comment by tthelen** [comment]
Christian prüft
