### ISSUE TITLE
Fatal Error nach Migration 18

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#327]
Fatal error: Undefined constant 'Mooc\REGISTRATION_FORM_CONFIG_ID' in /Projects/github/mooc.ip/migrations/018_add_registration_form_config.php on line 53

**Comment by luniki** [comment]
Einmal "composer update" und schon läufts wieder

**Comment by xabbuh** [comment]
Ich habe das Laden Konstanten in 50877a5496942089e3bd7ee16aae686f78710d7c auch mal den Composer-Autoloader übernehmen lassen.

**Comment by xabbuh** [comment]
Ach so, prinzipiell reicht dann auch `composer dump-autoload`.
