### ISSUE TITLE
SimpleORMap mag keine doppelten belongs_to

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#328]
Die gegenwärtige Implementation von SORM mag keine doppelten belongs_to wie in unseren Blocks. Die (natürlich undokumentierte) Lösung dafür ist, dass man die Relationsdefinitionen in eine #configure-Methode überträgt.

**Comment by xabbuh** [comment]
Was aber dann wiederum auch nur funktioniert, wenn man Stud.IP 3.1 einsetzt. Vorher gibt es noch keine Methode `configure()`.

**Comment by luniki** [comment]
ist jetzt behoben

**Comment by xabbuh** [comment]
Was war dafür noch notwendig? Oder reichte c600d7c6e25495c07f225684fc1c6aa32df330b7 aus?

**Comment by luniki** [comment]
siehe a2efeef86eb9ea017304fcdf7b71e609294dd90a
