### ISSUE TITLE
Seite neu laden nach Anlegen eines neuen Abschnitts ist sehr verwirrend

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#329]
Wenn man derzeit einen neuen Abschnitt anlegt, wird man direkt nach Anlegen auf die entsprechende Seite umgeleitet.

Wenn dieser Vorgang aber einige Zeit dauert, fängt der Nutzer uU an, andere Sachen (zb noch einen zweiten Abschnitt anlegen) einzurichten.

Mittendrin wird der Nutzer dann von diesem Neuladen unterbrochen.

Das kann so nicht bleiben.

**Comment by tthelen** [comment]
s. https://github.com/virtUOS/courseware/issues/68
