### ISSUE TITLE
Backlinks im Forum 

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/mooc.ip#334]
In der Bereichsbeschreibung einen Backlink hinterlegen zum Abschnitt in der Courseware

**Comment by tthelen** [comment]
Nix integrieren, einfach den Link BEIM ERZEUGEN der Beschreibung eintragen

**Comment by tgloeggl** [comment]
Backlink ist trotzdem problematisch: 
* Es können auch vorhandene Forenbereiche verknpüft werden -> Hinzufügen eines Backlinks zur Beschreibung zumindest unerwartet
* Ein Thema kann auch in mehreren Blöcken in unterschiedlicen Kapiteln verknüpft werden - wie geht man da mit dem Link um?

**Comment by tthelen** [comment]
Beim Erzeugen einer Verknüpfung soll der Backlink an die Beschreibung APPENDED werden, und zwar in der Form:

Dieser Bereich wird auf der Seite <verlinkter Abschnittstitel> verwendet. (<link>Zurück dorthin</link>)

**Comment by tgloeggl** [comment]
Das ganze wird mittels eines Markups realisiert. Es wird dafür ein eigenes Markup vom Plugin mitgeliefert, dass dann den entsprechenden Link generiert.
Das macht das bearbeiten der Beschreibung einfache und funktioniert sowohl mit als auch ohne WYSIWYG.
