### ISSUE TITLE
Dashboard - "Meine Kurse"

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/mooc.ip#340]
Es soll eine Liste der vom aktuell eingeloggten Nutzer belegten Kurse geben.
Außerdem soll es die Möglichkeit, sich direkt wieder aus einem Kurs auszutragen und eventuell auch die Kurslaufzeit anzeigen (siehe edX)

**Comment by tgloeggl** [comment]
@luniki Hast du vllt. in der Richtung ja schon was gemacht? Ansonsten morgen einfach besprechen mit @CGreweling

**Comment by CGreweling** [comment]
![bildschirmfoto vom 2015-02-16 11 55 43](https://cloud.githubusercontent.com/assets/3499600/6210746/e8d8c6f4-b5d2-11e4-9547-ab4abfc81c58.png)

**Comment by luniki** [comment]
Es gibt ja schon studip-ohn#6 Da werd ich drauf aufbauen.

**Comment by luniki** [comment]
@CGreweling Ich hätte gerne noch einen Screenshot mit einem aktuell laufendem edx-Kurs.

**Comment by CGreweling** [comment]
so?
![bildschirmfoto 2015-02-17 um 11 33 41](https://cloud.githubusercontent.com/assets/3499600/6226781/024abffe-b699-11e4-87bb-c2843662bfba.png)

**Comment by luniki** [comment]
Ja, super!

**Comment by luniki** [comment]
Bei mir sieht das derzeit dann so aus:
![selection_016](https://cloud.githubusercontent.com/assets/2993/6226808/40daa720-b699-11e4-8dfd-874575fb7901.png)

**Comment by luniki** [comment]
Nur das mit der Kurslaufzeit sollten wir noch absprechen. Ich mach mal dieses Issue zu und erstelle zwei weitere, speziellere.

**Comment by luniki** [comment]
@CGreweling Sieht der Screenshot so korrekt aus?

**Comment by CGreweling** [comment]
Ja das sieht gut aus. Das mit der Laufzeit sollten wir Donnerstag mal in die Runde werfen.

**Comment by CGreweling** [comment]
![auswahl_001](https://cloud.githubusercontent.com/assets/3499600/6265165/5c5925b0-b82b-11e4-9c8e-e356004319e2.png)
