### ISSUE TITLE
Mooc-Startseitenwidget automatisch zur Startseite Lernender hinzufügen

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#343]
Die Startseite von Lernenden sollte automatisch das Mooc-Startseitenwidget beinhalten, wenn das Mooc.IP-Plugin installiert ist.

@tthelen @CGreweling Das ist so richtig?

Dieses Ticket war ursprünglich Bestandteil von #340

**Comment by luniki** [comment]
Ich vermute, dass dieses Verhalten speziell für die OHN aber nicht generell gewünscht ist. Daher lohnt es sich wohl eher, dass händisch (wie gezeigt) in der Installation zu machen.

@CGreweling Reicht das für dich?

**Comment by CGreweling** [comment]
passt
