### ISSUE TITLE
In Kursberschreibung werden Bilder nicht angezeigt

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#348]
Bilder die öffentlich zugänglich sind aber nicht direkt im Kurs liegen werden auf der Kursübersichtsseite nicht angezeigt.

**Comment by luniki** [comment]
Das ist eine Einstellung der Stud.IP-Installation: LOAD_EXTERNAL_MEDIA

Diese muss passend eingestellt sein, damit das funktioniert.

**Comment by CGreweling** [comment]
wunderbar. :)
