### ISSUE TITLE
Nutzungsbedingungen lassen sich nicht ändern.

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#354]
Einloggen und sich für einen Kurs anmleden.
Die Nutzungsbedinungen sind hier die aus 
mooc.ip/migrations/018_add_registration_form_config.php
und nich was unter 
admin-> system -> Configuration-> global -> MOOC_TERMS_OF_SERVICE 
eingestellt ist.

**Comment by xabbuh** [comment]
In der Migration wird eigentlich nur ein initialer Text für genau diese Konfigurationsoption angelegt.

**Comment by luniki** [comment]
Muss im Stud.IP eingestellt werden:

**Comment by luniki** [comment]
Als root: Admin > System > Konfiguration > nach MOOC suchen

**Comment by CGreweling** [comment]
@luniki genau dass ist das Problem... dort sind andere Texte eingetragen als auf der Einloggen-Seite angezeigt werden

**Comment by luniki** [comment]
Hmm, also bei mir hier klappt das.
