### ISSUE TITLE
Studip-Markup funktioniert nicht in HTML-Block

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#355]

**Comment by CGreweling** [comment]
workaround:
/data/studip/public/plugins_packages/virtUOS/Mooc/blocks/HtmlBlock/HtmlBlock.php
 return array('content' => formatReady($this->content));

**Comment by luniki** [comment]
Du willst den WYSIWYG *und* Stud.IP-Markup haben? :dash:

**Comment by luniki** [comment]
Das telescopic plugin muss da rein
