### ISSUE TITLE
Vips Aufgaben nicht formatierbar

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#356]
Workaround:

Blocks/TestBlock/TestBlock.php
Zeile: 580
  /** 'description' => nl2br(htmlReady($this->test->description)),**/
          'description' => formatReady($this->test->description),
Zeile 561:
 'question' => formatReady($exercise->getQuestion()),

Mooc/blocks/TestBlock/templates/_question.mustache
Mooc/blocks/TestBlock/templates

(Antworten Formatierung fehlt noch)

**Comment by CGreweling** [comment]
"Irgendjemand" müsste das jetzt noch korrekt einbauen ;)

**Comment by CGreweling** [comment]
Der Workaorund scheint das Listenelemt in Lückentext-Vips zu zerstören...
[[*Rechner|*Aufgaben|*Links|Seiten|*Kommunikationsleitungen]]  wird jetzt nicht mehr dargestellt

**Comment by luniki** [comment]
Duplikat von #357
