### ISSUE TITLE
Studip-Markup wird in VIPS Multiple choice Fragen nicht umgesetzt

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#357]
Es funktioniert nicht in der Coursware, in der Vorschau unter Vips schon.
![multiplechoice_bilder](https://cloud.githubusercontent.com/assets/3499600/6505645/77cd9078-c344-11e4-9654-b2871ddbdf2e.png)

**Comment by luniki** [comment]
Schau mal, ob es jetzt so passt.

**Comment by CGreweling** [comment]
Ja das sieht gut aus. 
Es tritt jedoch noch ein Fehler beim Lückentext auf.
Wenn man die Lösung abgeshickt hat, wird der TAG {{ lösung anzeigen | Lösung }} nicht interpretiert.
![luckentext](https://cloud.githubusercontent.com/assets/3499600/6573298/d1c2296c-c719-11e4-8c45-a35a5ce12aef.png)
 
![luckentext_abgeshickt](https://cloud.githubusercontent.com/assets/3499600/6573300/d4b80876-c719-11e4-8f64-136f6cb39d48.png)
