### ISSUE TITLE
Übersetzung des Navigationsreiters "Courseware"

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#361]
Derzeit wird der Reiter nicht übersetzt. Ändern!

**Comment by luniki** [comment]
schau mal @CGreweling

**Comment by CGreweling** [comment]
@luniki ich habe den Patch gerade eingespielt. Leider taucht der String "Coursware" nicht in der po-datei auf. extractTranslationStrings wurde ausgeführt

**Comment by luniki** [comment]
Hmm, das liegt daran, dass extractTranslationStrings nicht über die Plugin-Verzeichnisse läuft. Entweder trägst du den String per Hand in die po-Datei ein oder ergänzt das Pluginverzeichnis im extractTranslationStrings-Skript

**Comment by CGreweling** [comment]
studip-ohn/issues/71
