### ISSUE TITLE
Dozenten können unter "TeilnerhmerInnen" nicht herabgestuft werden

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/mooc.ip#369]
Das kleine Kästchen zum anhaken wie bei Autoren und Tutoren fehlt.

**Comment by tgloeggl** [comment]
It's not a bug, it's a feature.
Das ist im Standard-Stud.IP absichtlich so gelöst. Zwischen Dozenten und Tutor/Autor/User gibt es eine mehr oder weniger rigide Trennung. Man kann auch keine Veranstaltungsteilnehmer einfach zum "Dozenten" hochstufen.
Über Sinn oder Unsinn lässt sich sicherlich trefflich streiten, but that's the way it is. :)
