### ISSUE TITLE
Zuordnungsaufgaben: Aufgabenblöcke nicht gleich hoch

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/mooc.ip#374]
Bei mehrzeiligen Texten in Zuordnungsaufgaben sind die ziehbaren Blöcke nicht immer gleich hoch. Das macht manche Aufgaben kaum bearbeitbar. Kann man die Höhe aller Blöcke an den höchsten Block anpassen?

**Comment by tthelen** [comment]
Der code ist eigentlich schon da: https://github.com/virtUOS/mooc.ip/blob/master/blocks/TestBlock/js/student_view.js#L53

**Comment by luniki** [comment]
@lkiesow Schau bitte einmal, ob es jetzt besser passt.

**Comment by CGreweling** [comment]
@lkiesow war gerade in der ecke...
Sieht gut aus!
