### ISSUE TITLE
Im- und Export des Forumsblocks

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/mooc.ip#377]

**Comment by tgloeggl** [comment]
Beim Import müssen die nun nihct mehr vorhandenen Bereiche mit neuen IDs neu angelegt werden.

**Comment by luniki** [comment]
Soll ich das in den courseware/dfb32 Branch mergen?

**Comment by tthelen** [comment]
Der Forumsblock wird da nicht verwendet, aber ein gleicher Stand wäre natürlich trotzdem gut.
