### ISSUE TITLE
Eingerückte Unter/kapitel mittels ++

### ISSUE THREAD

**Issue by luniki** [virtUOS/mooc.ip#378]
Das Feature ist jetzt in virtUOS/courseware sowohl im master als auch im dfb32 Branch. Für mooc.ip habe ich dafür einen Branch namens titleize angelegt: https://github.com/virtUOS/mooc.ip/tree/titleize

Dieser müsste noch einmal getestet und dann gemerged werden.

**Comment by CGreweling** [comment]
funktioniert leider nicht
