### ISSUE TITLE
Reiterlogik abhängig von isSlotModule

### ISSUE THREAD

**Issue by Krassmus** [virtUOS/mooc.ip#383]
Vielleicht spielt das mit #318 zusammen.

Das Plugin ist in getTabNavigation abhängig von der Funktion isSlotModule. Ist das Plugin nur über die Plus-Seite aktiviert, so fehlt der Reiter in der Veranstaltung. Warum das so ist, verstehe ich nicht. Vermutlich also ein Bug.

**Comment by tgloeggl** [comment]
Dieser Fix funktioniert erst dann komplett, wenn die enstprechende Fehlerbehebung in Stud.IP eingespielt ist: https://develop.studip.de/trac/ticket/6567

**Comment by tgloeggl** [comment]
Der Gedanke bei der Beschränkung auf isSlotModule war wohl, dass ein Dozent nicht seine Übersichtsseite selbst verändern darf, sondern dass durch einen Admin / root geschehen muss.
Mit der jetzt eingespielten Änderung in der Migration sehen Dozenten den Eintrag auch nicht mehr auf der Plus-Seite, es sei denn jemand aktiviert das explizit.
