### ISSUE TITLE
Übersetzen der Texte

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/mooc.ip#388]
Es gibt nun eine .po-Datei für das Plugin, es muss jetzt nur noch jemand die Texte übersetzen.

**Comment by tthelen** [comment]
Texte sind übersetzt, bitte mo-Datei erzeugen

**Comment by tgloeggl** [comment]
Hast du schon gepusht? Irgendwie sind die Änderungen noch nicht bei GitHub angekommen, oder vertu ich mich da grade...

**Comment by tthelen** [comment]
Jetzt aber...
